import os
import threading
import time
from flask import Flask, render_template, request, jsonify
from flask_socketio import SocketIO, emit
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
import base64
from gtts import gTTS
import requests

# Import our custom core components
from core.audio_io import AudioController
from core.brain import GarudaBrain
from core.database import VoiceLedger
from modules.agri_agent import AgricultureAgent
from modules.health_agent import HealthAgent
from modules.hunger_agent import ZeroHungerAgent

app = Flask(__name__)
app.config['SECRET_KEY'] = 'garuda_sanket_god_mode_2026'
socketio = SocketIO(app, cors_allowed_origins="*")

# Initialize global controllers
audio = AudioController()
brain = GarudaBrain()
ledger = VoiceLedger()
agri = AgricultureAgent(ledger, brain)
health = HealthAgent(ledger, brain)
hunger = ZeroHungerAgent(ledger, brain)

# Keep track of current session state
session = {
    "language": "en",
    "city": None,
    "domain": None,
    "user_phone": "9876543210" # Default for demo; in production, capture from gateway
}

@app.route('/')
def index():
    return render_template('dashboard.html')

@app.route('/buyer')
def buyer():
    return render_template('buyer_dashboard.html')

@app.route('/panchayat')
def panchayat():
    return render_template('panchayat_dashboard.html')

@app.route('/donor')
def donor():
    return render_template('donor_dashboard.html')

@app.route('/hospital')
def hospital():
    return render_template('hospital_dashboard.html')

@app.route('/microgrid')
def microgrid():
    return render_template('microgrid_dashboard.html')

@app.route('/cop')
def cop():
    return render_template('cop_dashboard.html')

@app.route('/send_pdf_report', methods=['POST'])
def send_pdf_report():
    try:
        data = request.json
        pdf_base64 = data.get('pdf_data')
        
        if not pdf_base64:
            return jsonify({'status': 'error', 'msg': 'No PDF data provided'}), 400

        # Decode base64
        pdf_data = base64.b64decode(pdf_base64.split(',')[1])

        # Email details
        sender_email = "u6973364@gmail.com"
        sender_password = "iquraorjiuvhrqsj"
        receiver_email = "u6973364@gmail.com"

        # Construct email
        msg = MIMEMultipart()
        msg['From'] = sender_email
        msg['To'] = receiver_email
        msg['Subject'] = "Panchayat Analytics Report - Garuda Sanket"

        body = "Attached is the latest Panchayat Analytics Dashboard report generated by the Garuda Sanket system."
        msg.attach(MIMEText(body, 'plain'))

        # Attach PDF
        part = MIMEApplication(pdf_data, Name="Panchayat_Analytics_Report.pdf")
        part['Content-Disposition'] = 'attachment; filename="Panchayat_Analytics_Report.pdf"'
        msg.attach(part)

        # Send Email
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(sender_email, sender_password)
        server.send_message(msg)
        server.quit()

        return jsonify({'status': 'success', 'msg': 'Email sent successfully'})
    except Exception as e:
        print(f"Error sending email: {e}")
        return jsonify({'status': 'error', 'msg': str(e)}), 500

# --- SOCKET EVENTS: DASHBOARD CONTROLS ---

@socketio.on('trigger_start')
def handle_start():
    print("\n[ACTION] New Call Triggered via Dashboard")
    emit('status_update', {'msg': 'Call Started from Remote'}, broadcast=True)
    
    text = "Welcome to Vistara AI. Please select your language. Press 1 for English and 2 for Kannada."
    path = generate_ai_voice(text, "en")
    try:
        print(f"\nOLLAMA RESPONSE : {text}")
    except UnicodeEncodeError:
        print(f"\nOLLAMA RESPONSE : (Vistara AI Intro)")
    emit('status_update', {'msg': f'AI: {text}'}, broadcast=True)
    audio.play_voice(path)

@socketio.on('select_language')
def handle_language(data):
    session['language'] = data['lang']
    print(f"\n[ACTION] Language Selected: {session['language'].upper()}")
    emit('status_update', {'msg': f'Language set to {data["lang"].upper()}'}, broadcast=True)
    # Play confirmation/next menu (City Selection)
    if session['language'] == 'en':
        text = "Press 1 for emergency for ambulance."
    else:
        text = "ಆಂಬ್ಯುಲೆನ್ಸ್ ತುರ್ತು ಪರಿಸ್ಥಿತಿಗಾಗಿ 1 ಅನ್ನು ಒತ್ತಿ."
        
    path = generate_ai_voice(text, session['language'])
    try:
        print(f"\nOLLAMA RESPONSE : {text}")
    except UnicodeEncodeError:
        print(f"\nOLLAMA RESPONSE : (Kannada Text - Display Error in Console)")
    emit('status_update', {'msg': f'AI: {text}'}, broadcast=True)
    audio.play_voice(path)

@socketio.on('select_location')
def handle_location(data):
    lat = data.get('lat')
    lng = data.get('lng')
    session['lat'] = lat
    session['lng'] = lng
    
    # Perform Reverse Geocoding to get real location name
    location_name = "Unknown Location"
    try:
        url = f"https://nominatim.openstreetmap.org/reverse?lat={lat}&lon={lng}&format=json"
        headers = {'User-Agent': 'GarudaSanketAI/1.0'}
        response = requests.get(url, headers=headers, timeout=5)
        if response.status_code == 200:
            json_data = response.json()
            location_name = json_data.get('display_name', 'Unknown Location')
    except Exception as e:
        location_name = "Could not fetch name"
        
    session['city'] = location_name
    print(f"\n[ACTION] Location Selected: {lat}, {lng}")
    print(f"[LOCATION NAME] {location_name}")
    
    emit('status_update', {'msg': f'Location set to Lat {lat}, Lng {lng}'}, broadcast=True)
    
    # After location is selected, ask for Domain (Emergency)
    if session['language'] == 'en':
        text = "Press 1 for emergency ambulance."
    else:
        text = "ತುರ್ತು ಆಂಬ್ಯುಲೆನ್ಸ್‌ಗಾಗಿ 1 ಒತ್ತಿ."
        
    path = generate_ai_voice(text, session['language'])
    try:
        print(f"\nOLLAMA RESPONSE : {text}")
    except UnicodeEncodeError:
        print(f"\nOLLAMA RESPONSE : (Kannada Text - Display Error in Console)")
    emit('status_update', {'msg': f'AI: {text}'}, broadcast=True)
    audio.play_voice(path)

@socketio.on('select_domain')
def handle_domain(data):
    session['domain'] = data['domain']
    print(f"\n[ACTION] Domain Selected: {session['domain'].upper()}")
    emit('status_update', {'msg': f'Domain Selected: {data["domain"].upper()}'}, broadcast=True)
    # Play specific sub-menu audio or welcome to the sector
    if session['domain'] == 'hunger':
        # Skip options, immediately process a general food request
        lang = session.get('language', 'en')
        text = "Your food request has been sent to the donors. Please wait while we find a match." if lang == 'en' else "ನಿಮ್ಮ ಆಹಾರದ ವಿನಂತಿಯನ್ನು ದಾನಿಗಳಿಗೆ ಕಳುಹಿಸಲಾಗಿದೆ. ದಯವಿಟ್ಟು ಕಾಯಿರಿ."
        
        # Notify Donors - Use socketio.emit for global broadcast
        socketio.emit('new_food_request', {
            'phone': session['user_phone'],
            'city': session.get('city', 'Unknown'),
            'type': 'General Food',
            'timestamp': time.strftime("%H:%M:%S"),
            'lat': data.get('lat'),
            'lng': data.get('lng')
        })
        
        try:
            print(f"\nOLLAMA RESPONSE : {text}")
        except UnicodeEncodeError:
            print(f"\nOLLAMA RESPONSE : (Kannada Text - Display Error in Console)")
        emit('status_update', {'msg': f'AI: {text}'}, broadcast=True)
        path = generate_ai_voice(text, lang)
        audio.play_voice(path)
        return # Exit early as we don't need further logic for this domain
        
    elif session['domain'] == 'agriculture':
        # (Currently deactivated as per user request)
        if session['language'] == 'en':
            text = "You selected Agriculture. Press 1 for Market Price, 2 for Pest Report, 3 for Sarkari Help."
        else:
            text = "ನೀವು ಕೃಷಿಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿದ್ದೀರಿ. ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಾಗಿ 1, ಕೀಟ ವರದಿಗಾಗಿ 2, ಸರ್ಕಾರಿ ಸಹಾಯಕ್ಕಾಗಿ 3 ಒತ್ತಿ."
    elif session['domain'] == 'health' or session['domain'] == 'healthcare':
        text = health.get_main_menu(session.get('language', 'en'))
    else:
        text = "Invalid domain."
            
    path = generate_ai_voice(text, session.get('language', 'en'))
    try:
        print(f"\nOLLAMA RESPONSE : {text}")
    except UnicodeEncodeError:
        print(f"\nOLLAMA RESPONSE : (Kannada Text - Display Error in Console)")
    emit('status_update', {'msg': f'AI: {text}'}, broadcast=True)
    audio.play_voice(path)

@socketio.on('health_action')
def handle_health_action(data):
    action = data['action']
    print(f"\n[ACTION] Health Action Triggered: {action.upper()}")
    emit('status_update', {'msg': f'Health Action: {action.upper()}'}, broadcast=True)
    lang = session.get('language', 'en')
    
    if action == 'bp':
        text = health.get_bp_menu(lang)
    elif action == 'symptom':
        intro = health.get_symptom_intro(lang)
        menu = health.get_symptom_menu(lang)
        text = f"{intro} {menu}"
    elif action == 'sugar':
        text = health.get_sugar_menu(lang)
    elif action == 'medicine':
        # Placeholder for Medicine Reminder
        text = health.get_medicine_reminder(lang)
    else:
        text = "Invalid selection."
        
    path = generate_ai_voice(text, lang)
    try:
        print(f"\nOLLAMA RESPONSE : {text}")
    except UnicodeEncodeError:
        print(f"\nOLLAMA RESPONSE : (Kannada Text - Display Error in Console)")
    emit('status_update', {'msg': f'AI: {text}'}, broadcast=True)
    audio.play_voice(path)

@socketio.on('sugar_action')
def handle_sugar_action(data):
    level = data['level']
    print(f"\n[ACTION] Sugar Action Triggered: {level.upper()}")
    emit('status_update', {'msg': f'Sugar Range: {level.upper()}'}, broadcast=True)
    lang = session.get('language', 'en')
    
    threading.Thread(target=audio.play_buffer).start()
    
    advice = health.get_sugar_advice(level, lang)
    safety = health.get_safety_message(lang)
    text = f"{advice} {safety}"
    
    try:
        print(f"\nOLLAMA RESPONSE : {text}")
    except UnicodeEncodeError:
        print(f"\nOLLAMA RESPONSE : (Kannada Text - Display Error in Console)")
    emit('status_update', {'msg': f'AI: {text}'}, broadcast=True)
    
    path = generate_ai_voice(text, lang)
    audio.stop_buffer()
    audio.play_voice(path)

@socketio.on('bp_action')
def handle_bp_action(data):
    level = data['level']
    print(f"\n[ACTION] BP Action Triggered: {level.upper()}")
    emit('status_update', {'msg': f'BP Range: {level.upper()}'}, broadcast=True)
    lang = session.get('language', 'en')
    
    threading.Thread(target=audio.play_buffer).start()
    
    advice = health.get_bp_advice(level, lang)
    safety = health.get_safety_message(lang)
    text = f"{advice} {safety}"
    
    try:
        print(f"\nOLLAMA RESPONSE : {text}")
    except UnicodeEncodeError:
        print(f"\nOLLAMA RESPONSE : (Kannada Text - Display Error in Console)")
    emit('status_update', {'msg': f'AI: {text}'}, broadcast=True)
    
    path = generate_ai_voice(text, lang)
    audio.stop_buffer()
    audio.play_voice(path)

@socketio.on('symptom_action')
def handle_symptom_action(data):
    symptom = data['symptom']
    print(f"\n[ACTION] Symptom Triggered: {symptom.upper()}")
    emit('status_update', {'msg': f'Symptom: {symptom.replace("_", " ").upper()}'}, broadcast=True)
    lang = session.get('language', 'en')
    
    threading.Thread(target=audio.play_buffer).start()
    
    advice = health.get_symptom_advice(symptom, lang)
    safety = health.get_safety_message(lang)
    text = f"{advice} {safety}"
    
    try:
        print(f"\nOLLAMA RESPONSE : {text}")
    except UnicodeEncodeError:
        print(f"\nOLLAMA RESPONSE : (Kannada Text - Display Error in Console)")
    emit('status_update', {'msg': f'AI: {text}'}, broadcast=True)
    
    path = generate_ai_voice(text, lang)
    audio.stop_buffer()
    audio.play_voice(path)


@socketio.on('agri_action')
def handle_agri(data):
    action = data['action']
    print(f"\n[ACTION] Agri Action Triggered: {action.upper()}")
    emit('status_update', {'msg': f'Agri Action: {action.replace("_", " ").upper()}'}, broadcast=True)
    
    # 1. Start thinking sound
    threading.Thread(target=audio.play_buffer).start()
    
    # 2. Process logic based on action
    if action == 'market_price':
        response_text = agri.get_market_intelligence(session['user_phone'], session['language'])
    elif action == 'pest_report':
        response_text = agri.process_pest_report(session['user_phone'], session['language'])
    elif action == 'sarkari_help':
        response_text = agri.get_scheme_eligibility(session['user_phone'], session['language'])
    else:
        if session['language'] == 'en':
            response_text = "I am ready to help with your farming needs."
        else:
            response_text = "ನಿಮ್ಮ ಕೃಷಿ ಅಗತ್ಯಗಳಿಗೆ ಸಹಾಯ ಮಾಡಲು ನಾನು ಸಿದ್ಧನಿದ್ದೇನೆ."

    # 3. TTS Generation & Playback
    path = generate_ai_voice(response_text, session['language'])
    try:
        print(f"\nOLLAMA RESPONSE : {response_text}")
    except UnicodeEncodeError:
        print(f"\nOLLAMA RESPONSE : (Kannada Text - Display Error in Console)")
    emit('status_update', {'msg': f'AI: {response_text}'}, broadcast=True)
    audio.play_voice(path)

@socketio.on('market_response')
def handle_market_response(data):
    response = data['response']
    print(f"\n[ACTION] Market Response: {response.upper()}")
    emit('status_update', {'msg': f'Market Response: {response.upper()}'}, broadcast=True)
    
    if response == 'agree':
        text = "Great! We have recorded your interest in selling at this rate. Our agent will contact you soon." if session['language'] == 'en' else "ಉತ್ತಮ! ಈ ದರದಲ್ಲಿ ಮಾರಾಟ ಮಾಡಲು ನಿಮ್ಮ ಆಸಕ್ತಿಯನ್ನು ನಾವು ದಾಖಲಿಸಿದ್ದೇವೆ. ನಮ್ಮ ಏಜೆಂಟ್ ಶೀಘ್ರದಲ್ಲೇ ನಿಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸುತ್ತಾರೆ."
        
        import random
        price = random.randint(2000, 3500)
        emit('buyer_email_alert', {
            'phone': session.get('user_phone', '9876543210'),
            'city': session.get('city', 'Unknown').upper() if session.get('city') else 'Unknown',
            'price': price
        }, broadcast=True)
    else:
        text = "No problem. We will notify you when the prices change." if session['language'] == 'en' else "ತೊಂದರೆಯಿಲ್ಲ. ಬೆಲೆಗಳು ಬದಲಾದಾಗ ನಾವು ನಿಮಗೆ ತಿಳಿಸುತ್ತೇವೆ."
        
    path = generate_ai_voice(text, session['language'])
    try:
        print(f"\nOLLAMA RESPONSE : {text}")
    except UnicodeEncodeError:
        print(f"\nOLLAMA RESPONSE : (Kannada Text - Display Error in Console)")
    emit('status_update', {'msg': f'AI: {text}'}, broadcast=True)
    audio.play_voice(path)

@socketio.on('pest_action')
def handle_pest_action(data):
    problem = data['problem']
    print(f"\n[ACTION] Pest Problem Reported: {problem.upper()}")
    emit('status_update', {'msg': f'Pest Problem: {problem.replace("_", " ").upper()}'}, broadcast=True)
    
    solution_text = agri.get_pest_solution(problem, session['language'])
    
    path = generate_ai_voice(solution_text, session['language'])
    try:
        print(f"\nOLLAMA RESPONSE : {solution_text}")
    except UnicodeEncodeError:
        print(f"\nOLLAMA RESPONSE : (Kannada Text - Display Error in Console)")
    emit('status_update', {'msg': f'AI: {solution_text}'}, broadcast=True)
    audio.play_voice(path)

@socketio.on('sarkari_action')
def handle_sarkari_action(data):
    acreage = data['acreage']
    print(f"\n[ACTION] Acreage Selected: {acreage.upper()}")
    emit('status_update', {'msg': f'Acreage: {acreage.replace("_", " ").upper()}'}, broadcast=True)
    
    scheme_text = agri.get_scheme_details(acreage, session['language'])
    
    # --- NEW CODE FOR PANCHAYAT ANALYTICS ---
    scheme_name = "Kisan Samman Nidhi" if acreage == 'small' else "PM-KUSUM (Solar Pump)"
    emit('update_scheme_analytics', {'scheme': scheme_name}, broadcast=True)
    # ----------------------------------------
    
    path = generate_ai_voice(scheme_text, session['language'])
    try:
        print(f"\nOLLAMA RESPONSE : {scheme_text}")
    except UnicodeEncodeError:
        print(f"\nOLLAMA RESPONSE : (Kannada Text - Display Error in Console)")
    emit('status_update', {'msg': f'AI: {scheme_text}'}, broadcast=True)
    audio.play_voice(path)

@socketio.on('sarkari_final')
def handle_sarkari_final(data):
    decision = data['decision']
    print(f"\n[ACTION] Scheme Submission Decision: {decision.upper()}")
    emit('status_update', {'msg': f'Submission: {decision.upper()}'}, broadcast=True)
    
    if decision == 'agree':
        text = "Your application has been submitted successfully. Thank you!" if session['language'] == 'en' else "ನಿಮ್ಮ ಅರ್ಜಿಯನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಸಲ್ಲಿಸಲಾಗಿದೆ. ಧನ್ಯವಾದಗಳು!"
    else:
        text = "Application cancelled. Let us know if you need help with anything else." if session['language'] == 'en' else "ಅರ್ಜಿಯನ್ನು ರದ್ದುಗೊಳಿಸಲಾಗಿದೆ. ನಿಮಗೆ ಬೇರೆ ಯಾವುದಾದರೂ ಸಹಾಯ ಬೇಕಾದಲ್ಲಿ ನಮಗೆ ತಿಳಿಸಿ."
        
    path = generate_ai_voice(text, session['language'])
    try:
        print(f"\nOLLAMA RESPONSE : {text}")
    except UnicodeEncodeError:
        print(f"\nOLLAMA RESPONSE : (Kannada Text - Display Error in Console)")
    audio.play_voice(path)

@socketio.on('emergency_trigger')
def handle_emergency(data):
    level = data['level'] # RED, YELLOW, GREEN
    print(f"\n[EMERGENCY] {level} LEVEL ACTIVATED")
    emit('status_update', {'msg': f'🚨 EMERGENCY ACTIVATED: {level}'}, broadcast=True)
    
    # Immediately stop any other audio
    audio.stop_buffer()
    
    if level == 'RED':
        # 1. Start Priority logic
        instructions = health.get_triage_instructions("RED", session['language'])
        # 2. Trigger Hospital Email in Background
        threading.Thread(target=health.trigger_hospital_alert, args=(session['user_phone'],)).start()
        # 3. Speak instructions
        path = generate_ai_voice(instructions, session['language'])
        try:
            print(f"\nOLLAMA RESPONSE : {instructions}")
        except UnicodeEncodeError:
            print(f"\nOLLAMA RESPONSE : (Kannada Text - Display Error in Console)")
        audio.play_voice(path)
    
    elif level == 'YELLOW':
        instructions = health.get_triage_instructions("YELLOW", session['language'])
        path = generate_ai_voice(instructions, session['language'])
        try:
            print(f"\nOLLAMA RESPONSE : {instructions}")
        except UnicodeEncodeError:
            print(f"\nOLLAMA RESPONSE : (Kannada Text - Display Error in Console)")
        audio.play_voice(path)
        
    elif level == 'GREEN':
        instructions = health.get_triage_instructions("GREEN", session['language'])
        path = generate_ai_voice(instructions, session['language'])
        try:
            print(f"\nOLLAMA RESPONSE : {instructions}")
        except UnicodeEncodeError:
            print(f"\nOLLAMA RESPONSE : (Kannada Text - Display Error in Console)")
        audio.play_voice(path)

# --- ZERO HUNGER EVENTS ---

@socketio.on('hunger_action')
def handle_hunger_action(data):
    action = data['action'] # 'request' or 'check'
    print(f"\n[ACTION] Hunger Action Triggered: {action.upper()}")
    emit('status_update', {'msg': f'Hunger Action: {action.upper()}'}, broadcast=True)
    lang = session.get('language', 'en')
    
    if action == 'request':
        text = hunger.get_food_type_menu(lang)
    else:
        text = "You have no active food requests at the moment." if lang == 'en' else "ನಿಮಗೆ ಯಾವುದೇ ಸಕ್ರಿಯ ಆಹಾರ ವಿನಂತಿಗಳಿಲ್ಲ."
        
    path = generate_ai_voice(text, lang)
    try:
        print(f"\nOLLAMA RESPONSE : {text}")
    except UnicodeEncodeError:
        print(f"\nOLLAMA RESPONSE : (Kannada Text - Display Error in Console)")
    emit('status_update', {'msg': f'AI: {text}'}, broadcast=True)
    audio.play_voice(path)

@socketio.on('food_type_action')
def handle_food_type(data):
    food_type = data['type'] # 'grains', 'cooked', 'baby'
    print(f"\n[ACTION] Food Type Selected: {food_type.upper()}")
    emit('status_update', {'msg': f'Food Requested: {food_type.upper()}'}, broadcast=True)
    lang = session.get('language', 'en')
    
    threading.Thread(target=audio.play_buffer).start()
    
    response_text = hunger.process_request(session['user_phone'], lang, food_type, session.get('city', 'Unknown'))
    
    # Notify Donors - Use socketio.emit for global broadcast
    print(f"[BROADCAST] Notifying donors about {food_type} request")
    socketio.emit('new_food_request', {
        'phone': session['user_phone'],
        'city': session.get('city', 'Unknown'),
        'type': food_type,
        'timestamp': time.strftime("%H:%M:%S")
    })
    
    path = generate_ai_voice(response_text, lang)
    try:
        print(f"\nOLLAMA RESPONSE : {response_text}")
    except UnicodeEncodeError:
        print(f"\nOLLAMA RESPONSE : (Kannada Text - Display Error in Console)")
    emit('status_update', {'msg': f'AI: {response_text}'}, broadcast=True)
    audio.stop_buffer()
    audio.play_voice(path)

@socketio.on('donor_accept')
def handle_donor_accept(data):
    requester_phone = data['phone']
    donor_name = data.get('donor_name', 'A kind donor')
    print(f"\n[DONOR] Request Accepted by {donor_name} for {requester_phone}")
    
    emit('status_update', {'msg': f'Donor {donor_name} accepted request!'}, broadcast=True)
    
    lang = session.get('language', 'en')
    text = hunger.get_donor_acceptance_message(donor_name, lang)
    
    path = generate_ai_voice(text, lang)
    try:
        print(f"\nOLLAMA RESPONSE : {text}")
    except UnicodeEncodeError:
        print(f"\nOLLAMA RESPONSE : (Kannada Text - Display Error in Console)")
    emit('status_update', {'msg': f'AI (To User): {text}'}, broadcast=True)
    audio.play_voice(path)
    # Also notify the dashboard to show the Dial button
    emit('donor_accepted_notify', {'donor_name': donor_name}, broadcast=True)

@socketio.on('donor_dial')
def handle_donor_dial():
    print(f"\n[ACTION] User Dialing Donor")
    emit('status_update', {'msg': 'Dialing donor... connecting call.'}, broadcast=True)
    lang = session.get('language', 'en')
    text = "Connecting your call to the donor. Please stay on the line. Thank you for using Zero Hunger." if lang == 'en' else "ದಾನಿಗಳೊಂದಿಗೆ ನಿಮ್ಮ ಕರೆಯನ್ನು ಸಂಪರ್ಕಿಸಲಾಗುತ್ತಿದೆ. ದಯವಿಟ್ಟು ಲೈನ್‌ನಲ್ಲಿರಿ. ಜೀರೋ ಹಂಗರ್ ಬಳಸಿದ್ದಕ್ಕಾಗಿ ಧನ್ಯವಾದಗಳು."
    path = generate_ai_voice(text, lang)
    try:
        print(f"\nOLLAMA RESPONSE : {text}")
    except UnicodeEncodeError:
        print(f"\nOLLAMA RESPONSE : (Kannada Text - Display Error in Console)")
    audio.play_voice(path)

# --- VĀYU-HOSPITAL TACTICAL DISPATCH EVENTS ---

@socketio.on('trigger_emergency_tmt')
def handle_trigger_tmt(data):
    """Broadcasts the TMT Token to all hospital dashboards."""
    patient_id = f"PAT-{int(time.time()) % 10000}"
    lat = data.get('lat', 13.0033) # Default near Malleshwaram
    lng = data.get('lng', 77.5640)
    severity = data.get('severity', 'RED')
    
    import random
    contact_hash = '#' + ''.join(random.choices('0123456789abcdef', k=8))
    location_hash = '#' + ''.join(random.choices('0123456789abcdef', k=8))
    
    print(f"\nOLLAMA RESPONSE : TMT Broadcast Triggered")
    print(f"Patient ID: {patient_id}")
    print(f"Location: [{lat}, {lng}]")
    print(f"Severity: {severity}")
    print(f"Contact Hash: {contact_hash}")
    print(f"Location Hash: {location_hash}")
    emit('status_update', {'msg': f'🚨 Vāyu Emergency Broadcast: {patient_id}'}, broadcast=True)
    
    socketio.emit('new_tmt_token', {
        'patient_id': patient_id,
        'lat': lat,
        'lng': lng,
        'severity': severity,
        'timestamp': time.strftime("%H:%M:%S"),
        'phone': session.get('user_phone', '9876543210'),
        'contact_hash': contact_hash,
        'location_hash': location_hash
    })
    
    lang = session.get('language', 'en')
    if lang == 'en':
        text = "We have completed your process. You will shortly get a call from the hospital."
    else:
        text = "ನಾವು ನಿಮ್ಮ ಪ್ರಕ್ರಿಯೆಯನ್ನು ಪೂರ್ಣಗೊಳಿಸಿದ್ದೇವೆ. ನೀವು ಶೀಘ್ರದಲ್ಲೇ ಆಸ್ಪತ್ರೆಯಿಂದ ಕರೆಯನ್ನು ಪಡೆಯುತ್ತೀರಿ."
    path = generate_ai_voice(text, lang)
    audio.play_voice(path)

@socketio.on('accept_tmt')
def handle_accept_tmt(data):
    """Concurrency Controller: Locks the state when a hospital accepts."""
    patient_id = data.get('patient_id')
    hospital_name = data.get('hospital_name', 'Unknown Hospital')
    
    print(f"\n[VĀYU-HOSPITAL HANDSHAKE] TMT {patient_id} ACCEPTED by {hospital_name}")
    
    # Broadcast to all hospitals that the case is handled
    socketio.emit('tmt_resolved', {
        'patient_id': patient_id,
        'accepted_by': hospital_name
    })
    
    # Audio feedback to the user
    lang = session.get('language', 'en')
    text = f"An ambulance has been dispatched from {hospital_name}." if lang == 'en' else f"{hospital_name} ಯಿಂದ ಆಂಬ್ಯುಲೆನ್ಸ್ ಅನ್ನು ಕಳುಹಿಸಲಾಗಿದೆ."
    path = generate_ai_voice(text, lang)
    audio.play_voice(path)

@socketio.on('trigger_green_channel')
def handle_trigger_green_channel(data):
    """Phase 2: Initiates Green-Channel Route and Traffic Analytics."""
    print(f"\n[VISTAAR TRAFFIC COMMAND] Green-Channel Requested for {data.get('patient_id')}")
    
    # Generate OLLAMA RESPONSE for routing logic
    reasoning = "OLLAMA RESPONSE : I chose this route because it avoids the 85% congestion rate at the Central Silk Board choke point. By utilizing the 100ft Arterial road, we create a bidirectional corridor ensuring a 15-minute time saving for both inbound pickup and outbound emergency drop-off. Traffic police data bursts successfully queued."
    print(reasoning)
    
    emit('status_update', {'msg': 'Phase 2: Bidirectional Green-Channel Active'}, broadcast=True)

@socketio.on('trigger_cop_call')
def handle_trigger_cop_call(data):
    """Triggered when the hospital explicitly confirms the calculated route."""
    print(f"\n[VISTAAR TRAFFIC COMMAND] Dispatching Route to Cops for {data.get('patient_id')}")
    # Trigger standalone dashboard animation
    emit('incoming_cop_call', {'patient_id': data.get('patient_id')}, broadcast=True)

@socketio.on('cop_call_accepted')
def handle_cop_call_accepted(data):
    """Handles the ambulance driver or cop acknowledging the route."""
    node = data.get('node', 'Junction')
    print(f"\nOLLAMA RESPONSE : {node} ACKNOWLEDGED the Green-Channel request. Lane 1 is being cleared. TMT-Token prioritized.")
    emit('status_update', {'msg': f'{node} Route Acknowledged'}, broadcast=True)

# --- HELPER FUNCTIONS ---


def generate_ai_voice(text, lang):
    """
    Utility to bridge Brain text output to Audio playback.
    Uses unique filenames to avoid Windows file-locking issues.
    """
    # Create unique filename using timestamp
    filename = f"reply_{int(time.time() * 1000)}.mp3"
    file_path = os.path.abspath(os.path.join("static", "audio", filename))
    
    # Ensure directory exists
    os.makedirs(os.path.dirname(file_path), exist_ok=True)
    
    try:
        tts = gTTS(text, lang=lang)
        tts.save(file_path)
        print(f"OLLAMA RESPONSE : {text}")
    except Exception as e:
        print(f"Error generating TTS: {e}")
        
    return file_path

if __name__ == '__main__':
    print("Vistara AI Server Active (HTTP Mode)...")
    socketio.run(app, debug=True, host='0.0.0.0', port=5000, allow_unsafe_werkzeug=True)